In [19]:
import numpy as np
from numpy import genfromtxt

from keras.models import Sequential
from keras.layers import Dense

from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix, classification_report

In [4]:
data = r'C:\Users\Abhiram Challapalli\Documents\DATA'
bank = genfromtxt(data+'\\bank_note_data.txt', delimiter=',')

In [5]:
bank,bank.shape

(array([[  3.6216 ,   8.6661 ,  -2.8073 ,  -0.44699,   0.     ],
        [  4.5459 ,   8.1674 ,  -2.4586 ,  -1.4621 ,   0.     ],
        [  3.866  ,  -2.6383 ,   1.9242 ,   0.10645,   0.     ],
        ...,
        [ -3.7503 , -13.4586 ,  17.5932 ,  -2.7771 ,   1.     ],
        [ -3.5637 ,  -8.3827 ,  12.393  ,  -1.2823 ,   1.     ],
        [ -2.5419 ,  -0.65804,   2.6842 ,   1.1952 ,   1.     ]]), (1372, 5))

In [6]:
labels = bank[:,4]
features = bank[:,0:4]
X = features
y = labels

In [7]:
X_train, X_test, y_train, y_test = train_test_split(X,y, test_size=0.2, random_state=42)

In [23]:
len(X_train)

1097

In [8]:
from sklearn.preprocessing import MinMaxScaler
scale = MinMaxScaler()
scale.fit(X_train)
scaled_x_train = scale.transform(X_train)
scaled_x_test = scale.transform(X_test)

# we don't fit to test data because the scaler will have a look at the test set. it's called data leakage

In [9]:
scaled_x_train.min(), scaled_x_train.max()

(0.0, 1.0000000000000002)

In [10]:
model = Sequential()

model.add(Dense(4, input_dim=4, activation='relu'))
model.add(Dense(8, activation='relu'))
model.add(Dense(8, activation='relu'))

model.add(Dense(1, activation='sigmoid'))

In [12]:
model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])

In [16]:
model.fit(scaled_x_train, y_train, epochs=99, verbose=2)

Epoch 1/99
 - 0s - loss: 0.0201 - accuracy: 0.9891
Epoch 2/99
 - 0s - loss: 0.0190 - accuracy: 0.9909
Epoch 3/99
 - 0s - loss: 0.0193 - accuracy: 0.9909
Epoch 4/99
 - 0s - loss: 0.0199 - accuracy: 0.9909
Epoch 5/99
 - 0s - loss: 0.0221 - accuracy: 0.9900
Epoch 6/99
 - 0s - loss: 0.0216 - accuracy: 0.9909
Epoch 7/99
 - 0s - loss: 0.0222 - accuracy: 0.9891
Epoch 8/99
 - 0s - loss: 0.0208 - accuracy: 0.9918
Epoch 9/99
 - 0s - loss: 0.0198 - accuracy: 0.9909
Epoch 10/99
 - 0s - loss: 0.0193 - accuracy: 0.9881
Epoch 11/99
 - 0s - loss: 0.0209 - accuracy: 0.9872
Epoch 12/99
 - 0s - loss: 0.0195 - accuracy: 0.9909
Epoch 13/99
 - 0s - loss: 0.0192 - accuracy: 0.9900
Epoch 14/99
 - 0s - loss: 0.0173 - accuracy: 0.9954
Epoch 15/99
 - 0s - loss: 0.0238 - accuracy: 0.9900
Epoch 16/99
 - 0s - loss: 0.0202 - accuracy: 0.9909
Epoch 17/99
 - 0s - loss: 0.0205 - accuracy: 0.9918
Epoch 18/99
 - 0s - loss: 0.0195 - accuracy: 0.9927
Epoch 19/99
 - 0s - loss: 0.0185 - accuracy: 0.9945
Epoch 20/99
 - 0s - l

In [17]:
model.predict_classes(scaled_x_test)

array([[0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [1],
       [0],
       [1],
       [0],
       [1],
       [1],
       [1],
       [1],
       [1],
       [0],
       [0],
       [1],
       [0],
       [1],
       [0],
       [0],
       [1],
       [0],
       [0],
       [1],
       [0],
       [0],
       [1],
       [1],
       [0],
       [1],
       [1],
       [1],
       [0],
       [0],
       [1],
       [1],
       [0],
       [1],
       [1],
       [1],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [1],
       [0],
       [1],
       [0],
       [1],
       [1],
       [0],
       [1],
       [1],
       [1],
       [1],
       [0],
       [1],
    

In [18]:
model.metrics_names

['loss', 'accuracy']

In [20]:
from sklearn.metrics import confusion_matrix, classification_report

In [21]:
predictions = model.predict_classes(scaled_x_test)

In [22]:
confusion_matrix(y_test, predictions)

array([[146,   2],
       [  2, 125]], dtype=int64)

In [23]:
print(classification_report(y_test, predictions))

              precision    recall  f1-score   support

         0.0       0.99      0.99      0.99       148
         1.0       0.98      0.98      0.98       127

    accuracy                           0.99       275
   macro avg       0.99      0.99      0.99       275
weighted avg       0.99      0.99      0.99       275



In [35]:
z = []
for i in y_test:
    if i == 0:
        z.append(i)

In [36]:
len(z)

148

In [34]:
len(y_test)

275

In [37]:
model.save('bank.h5')

In [ ]:
from keras.models import load_model
new = load_model('bank.h5')